"""
Contract Sender Agent — sends a generated contract via Gmail and/or WhatsApp (Twilio).
"""
import os
import base64
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from typing import Dict

# Gmail SMTP (reuses existing .env vars)
SMTP_HOST     = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT     = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER     = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")

# Twilio WhatsApp
TWILIO_ACCOUNT_SID  = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN   = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_FROM = os.getenv("TWILIO_WHATSAPP_FROM", "whatsapp:+14155238886")  # Twilio sandbox number


def send_contract_email(
    to_email: str,
    subject: str,
    contract_text: str,
    filename: str,
    sender_note: str = "",
) -> Dict:
    """Send contract as .txt attachment via Gmail SMTP."""
    if not SMTP_USER or not SMTP_PASSWORD:
        return {"success": False, "error": "SMTP credentials not configured in .env"}

    try:
        msg = MIMEMultipart()
        msg["From"]    = SMTP_USER
        msg["To"]      = to_email
        msg["Subject"] = subject

        # Email body
        body_html = f"""
<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:24px">
  <h2 style="color:#0f172a">⚖ Contract from LexAgent</h2>
  <p style="color:#334155">Please find the attached contract for your review.</p>
  {f'<p style="color:#334155"><em>{sender_note}</em></p>' if sender_note else ''}
  <p style="color:#334155">The contract has been generated by LexAgent and is attached as a <code>.txt</code> file.</p>
  <hr style="border:none;border-top:1px solid #e2e8f0;margin:20px 0">
  <p style="color:#94a3b8;font-size:12px">Sent by LexAgent · AI-powered contract platform · This is not legal advice.</p>
</div>
"""
        msg.attach(MIMEText(body_html, "html"))

        # Attach contract as .txt
        attachment = MIMEBase("text", "plain")
        attachment.set_payload(contract_text.encode("utf-8"))
        encoders.encode_base64(attachment)
        attachment.add_header(
            "Content-Disposition",
            f'attachment; filename="{filename}"',
        )
        msg.attach(attachment)

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)

        return {"success": True, "to": to_email}

    except Exception as e:
        return {"success": False, "error": str(e)}


def send_contract_whatsapp(
    to_number: str,
    contract_label: str,
    filename: str,
    sender_note: str = "",
) -> Dict:
    """
    Send a WhatsApp message via Twilio notifying about the contract.
    WhatsApp can't receive file attachments directly via Twilio sandbox,
    so we send a message summary instead.
    """
    if not TWILIO_ACCOUNT_SID or not TWILIO_AUTH_TOKEN:
        return {"success": False, "error": "Twilio credentials not configured in .env"}

    try:
        from twilio.rest import Client
        client = Client(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)

        # Normalise number — ensure whatsapp: prefix
        to_wa = to_number if to_number.startswith("whatsapp:") else f"whatsapp:{to_number}"

        body = (
            f"📄 *Contract Ready — {contract_label}*\n\n"
            f"A contract has been generated and sent to your email as *{filename}*.\n"
            f"{f'{sender_note}' + chr(10) if sender_note else ''}"
            f"\nReviewed by LexAgent · AI-powered contract platform."
        )

        message = client.messages.create(
            from_=TWILIO_WHATSAPP_FROM,
            to=to_wa,
            body=body,
        )

        return {"success": True, "sid": message.sid, "to": to_wa}

    except ImportError:
        return {"success": False, "error": "twilio package not installed. Run: pip install twilio"}
    except Exception as e:
        return {"success": False, "error": str(e)}


def send_contract(
    contract_text: str,
    contract_label: str,
    filename: str,
    to_email: str = "",
    to_whatsapp: str = "",
    subject: str = "",
    sender_note: str = "",
) -> Dict:
    """Send contract via all configured channels. Returns results per channel."""
    results = {}
    subject = subject or f"Contract: {contract_label}"

    if to_email:
        results["email"] = send_contract_email(
            to_email, subject, contract_text, filename, sender_note
        )

    if to_whatsapp:
        results["whatsapp"] = send_contract_whatsapp(
            to_whatsapp, contract_label, filename, sender_note
        )

    return results
